#!/usr/bin/env bash
# Install and configure Load Balancer

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy 
sudo chown -R ubuntu /etc/haproxy
sudo echo "

frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 3357-web-01 35.243.136.3:80 check
        server 3357-web-02 3.89.56.35:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
